name: 'Do It Later'
description: 'Read from github issues and send to your telegram chat'
inputs:
  token: 
    description: 'Github Personal Access Token'
    required: true
  functions_endpoint: 
    description: 'Azure functions (Project) Endpoint'
    required: true
  host_key: 
    description: 'Azure functions Host Key'
    required: true
outputs:
  issues:
    description: 'All issues that we sent'
  transformedIssues:
    description: 'All issues that we transorm as chat message'
runs:
  using: 'node16'
  main: 'dist-action/index.js'