on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tegarimansyah/doitlater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          functions_endpoint: ${{ secrets.FUNCTIONS_ENDPOINT }}
          host_key: ${{ secrets.HOST_KEY }}


      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"