on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tegarimansyah/doitlater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          functions_endpoint: ${{ secrets.FUNCTIONS_ENDPOINT }}
          host_key: ${{ secrets.HOST_KEY }}

      - name: Get issues that we sent
        run: echo "${{ steps.hello.outputs.issues }}"