name: Get Issues Weekly

on:
  schedule:
    # Since github schedule run on UTC, we need to change it to our timezone
    - cron: "0 1 * * SUN"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Github Issue and Send
        id: get-github-issue
        uses: tegarimansyah/doitlater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          functions_endpoint: ${{ secrets.FUNCTIONS_ENDPOINT }}
          host_key: ${{ secrets.HOST_KEY }}